import { IsUrl, ValidateIf } from 'class-validator';
import { isManagedUpload } from '../services/livetv-playlist-file';

/**
 * An m3u source location is a fetchable URL, or the path this server
 * generated by storing an upload (`POST sources/playlist`) — never a
 * filesystem path an admin typed by hand, which would let `readLocalPlaylist`
 * read an arbitrary file.
 */
export function IsPlaylistLocation(): PropertyDecorator {
  return (target, propertyKey) => {
    ValidateIf((o: Record<string, unknown>) => {
      const value = o[propertyKey as string];
      return typeof value !== 'string' || !isManagedUpload(value);
    })(target, propertyKey);
    IsUrl({ require_tld: false, require_protocol: true })(target, propertyKey);
  };
}
