import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1777816212948 implements MigrationInterface {
    name = 'Baseline1777816212948'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "root_folders" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "path" character varying NOT NULL, "label" character varying, "libraryId" integer, CONSTRAINT "UQ_da29637e4e583bf0ee7b3317f05" UNIQUE ("path"), CONSTRAINT "PK_7f6b8066e41c3b0507db3a334b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quality_profiles" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "cutoff" integer NOT NULL, "items" jsonb NOT NULL, "upgradeAllowed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_77c6c3df9cc1a3f59166dc60764" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "language_profiles" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "audioLanguages" jsonb NOT NULL DEFAULT '[]', "subtitleLanguages" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_bf8bfa8caf3eece3d5224afe2be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "libraries" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "icon" character varying(48), "color" character varying(32), "mediaTypes" jsonb NOT NULL DEFAULT '["movie","series"]', "preferredProvider" character varying, "stalledCleanupProfile" character varying(16), "isDefaultForMovies" boolean NOT NULL DEFAULT false, "isDefaultForSeries" boolean NOT NULL DEFAULT false, "defaultQualityProfileId" integer, "defaultLanguageProfileId" integer, CONSTRAINT "UQ_9fb3b11b4181af695b7cbf06d49" UNIQUE ("name"), CONSTRAINT "PK_505fedfcad00a09b3734b4223de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "permissions" text NOT NULL DEFAULT '[]', "isDefault" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_mediaservertype_enum" AS ENUM('local', 'jellyfin', 'emby', 'plex')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "username" character varying NOT NULL, "email" character varying, "passwordHash" character varying, "roleId" integer, "mediaServerType" "public"."users_mediaservertype_enum" NOT NULL DEFAULT 'local', "mediaServerId" character varying, "avatar" character varying, "lastLogin" TIMESTAMP WITH TIME ZONE, "isAdmin" boolean NOT NULL DEFAULT false, "enabled" boolean NOT NULL DEFAULT true, "requirePasswordChange" boolean NOT NULL DEFAULT false, "movieQuotaLimit" integer NOT NULL DEFAULT '0', "seriesQuotaLimit" integer NOT NULL DEFAULT '0', "quotaPeriodDays" integer NOT NULL DEFAULT '7', CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."media_servers_type_enum" AS ENUM('local', 'jellyfin', 'emby', 'plex')`);
        await queryRunner.query(`CREATE TABLE "media_servers" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "type" "public"."media_servers_type_enum" NOT NULL, "url" character varying NOT NULL, "apiKey" character varying, "events" jsonb NOT NULL DEFAULT '[]', "enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c7f56b22b880f2d948ffe50b83e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subtitle_providers_type_enum" AS ENUM('opensubtitles', 'subscene', 'sous_titres_eu', 'subdl', 'subsynchro', 'supersubtitles', 'whisper', 'yify', 'gestdown', 'embedded', 'radarr', 'sonarr', 'disk')`);
        await queryRunner.query(`CREATE TABLE "subtitle_providers" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "type" "public"."subtitle_providers_type_enum" NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "settings" jsonb NOT NULL DEFAULT '{}', "priority" integer NOT NULL DEFAULT '25', CONSTRAINT "PK_a9b2861711c6befdee0953d3994" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subtitle_provider_stats" ("id" SERIAL NOT NULL, "queryDate" TIMESTAMP NOT NULL DEFAULT now(), "queryType" character varying NOT NULL DEFAULT 'search', "responseTimeMs" integer NOT NULL DEFAULT '0', "resultCount" integer NOT NULL DEFAULT '0', "errorMessage" text, "providerId" integer, CONSTRAINT "PK_07ed845bbe29f017fbadb2e1e06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "episodes" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "episodeNumber" integer NOT NULL, "endEpisodeNumber" integer, "title" character varying, "overview" text, "airDate" date, "runtime" integer, "monitored" boolean NOT NULL DEFAULT true, "hasFile" boolean NOT NULL DEFAULT false, "stillUrl" text, "markersScannedAt" TIMESTAMP WITH TIME ZONE, "searchVector" tsvector, "seasonId" integer, CONSTRAINT "PK_6a003fda8b0473fffc39cb831c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seasons" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "seasonNumber" integer NOT NULL, "monitored" boolean NOT NULL DEFAULT true, "preferredProvider" character varying(16), "mediaId" integer, CONSTRAINT "PK_cb8ed53b5fe109dcd4a4449ec9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media_files" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "relativePath" character varying NOT NULL, "size" bigint NOT NULL, "quality" character varying NOT NULL, "language" character varying, "streamInfo" jsonb, "mediaId" integer, "episodeId" integer, CONSTRAINT "UQ_89a6bf94332e9f2715c4d06b36c" UNIQUE ("mediaId", "relativePath"), CONSTRAINT "PK_93b4da6741cd150e76f9ac035d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media_metadata" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "budget" bigint, "revenue" bigint, "tagline" character varying, "popularity" double precision, "voteCount" integer, "originalLanguage" character varying, "productionCountries" jsonb, "productionCompanies" jsonb, "videos" jsonb, "keywords" jsonb, "mediaId" integer, CONSTRAINT "REL_62d457c000de0f01b2821a06ae" UNIQUE ("mediaId"), CONSTRAINT "PK_6c52273ad7331542bbce7ae4da1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "persons" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tmdbId" integer NOT NULL, "name" character varying NOT NULL, "avatarUrl" character varying, "biography" text, "birthday" date, "deathday" date, "placeOfBirth" character varying, "knownForDepartment" character varying, "departments" jsonb NOT NULL DEFAULT '[]', "metadataRefreshedAt" TIMESTAMP WITH TIME ZONE, "searchVector" tsvector, CONSTRAINT "UQ_4069db2315833af2a2bcdc59c42" UNIQUE ("tmdbId"), CONSTRAINT "PK_74278d8812a049233ce41440ac7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media_cast" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "character" character varying NOT NULL, "order" integer NOT NULL, "mediaId" integer, "personId" integer, CONSTRAINT "PK_444fff397439c1f5b7918ebc5ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f702d61f4cd1578c889ab3cadc" ON "media_cast" ("personId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cc8df2e63ef1cd8cf28bfc854" ON "media_cast" ("mediaId") `);
        await queryRunner.query(`CREATE TABLE "media_crew" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "job" character varying NOT NULL, "department" character varying NOT NULL, "mediaId" integer, "personId" integer, CONSTRAINT "PK_5eac3317df46210d0bd248d432d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8226529bf8b570cefa0bad2f96" ON "media_crew" ("personId") `);
        await queryRunner.query(`CREATE INDEX "IDX_95c3254f4a9023b7f30c81c25f" ON "media_crew" ("mediaId") `);
        await queryRunner.query(`CREATE TYPE "public"."media_type_enum" AS ENUM('movie', 'series')`);
        await queryRunner.query(`CREATE TYPE "public"."media_status_enum" AS ENUM('tba', 'announced', 'released', 'ended', 'continuing', 'deleted')`);
        await queryRunner.query(`CREATE TABLE "media" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "originalTitle" character varying, "year" integer, "type" "public"."media_type_enum" NOT NULL, "tmdbId" integer, "imdbId" character varying, "tvdbId" integer, "overview" text, "status" "public"."media_status_enum" NOT NULL DEFAULT 'tba', "monitored" boolean NOT NULL DEFAULT true, "preferredProvider" character varying(16), "folderName" character varying, "posterUrl" character varying, "metadataRefreshedAt" TIMESTAMP WITH TIME ZONE, "fanartUrl" character varying, "rating" double precision, "genres" jsonb, "runtime" integer, "releaseDate" date, "inCinemas" date, "digitalRelease" date, "physicalRelease" date, "minimumAvailability" character varying NOT NULL DEFAULT 'released', "searchVector" tsvector, "rootFolderId" integer, "libraryId" integer, "qualityProfileId" integer, "languageProfileId" integer, CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_media_type_tmdbId" ON "media" ("type", "tmdbId") `);
        await queryRunner.query(`CREATE TYPE "public"."subtitle_files_providertype_enum" AS ENUM('opensubtitles', 'subscene', 'sous_titres_eu', 'subdl', 'subsynchro', 'supersubtitles', 'whisper', 'yify', 'gestdown', 'embedded', 'radarr', 'sonarr', 'disk')`);
        await queryRunner.query(`CREATE TYPE "public"."subtitle_files_status_enum" AS ENUM('missing', 'downloaded', 'upgraded', 'synced', 'failed', 'embedded')`);
        await queryRunner.query(`CREATE TABLE "subtitle_files" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "language" character varying NOT NULL, "forced" boolean NOT NULL DEFAULT false, "hearingImpaired" boolean NOT NULL DEFAULT false, "providerType" "public"."subtitle_files_providertype_enum" NOT NULL, "providerFileId" character varying, "filePath" character varying, "status" "public"."subtitle_files_status_enum" NOT NULL DEFAULT 'downloaded', "streamIndex" integer, "codec" character varying, "score" integer NOT NULL DEFAULT '0', "synced" boolean NOT NULL DEFAULT false, "syncOffset" integer, "locked" boolean NOT NULL DEFAULT false, "tags" text NOT NULL DEFAULT '[]', "mediaId" integer, "episodeId" integer, "mediaFileId" integer, CONSTRAINT "PK_1d4ab28141e13ad42262cab12b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subtitle_blacklist" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "providerType" character varying NOT NULL, "providerFileId" character varying NOT NULL, "language" character varying, "sourceTitle" character varying, "reason" character varying, "mediaId" integer, CONSTRAINT "PK_3f978f16e490f314ac14a3b4a6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recommendation_dismissals" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "mediaId" integer NOT NULL, CONSTRAINT "PK_d64fd0160e105d4bcbaa1829711" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2675281c4a4e36f69c7a07bff7" ON "recommendation_dismissals" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_recommendation_dismissals_user_media" ON "recommendation_dismissals" ("userId", "mediaId") `);
        await queryRunner.query(`CREATE TABLE "playback_states" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "positionSeconds" double precision NOT NULL DEFAULT '0', "durationSeconds" double precision DEFAULT '0', "completed" boolean NOT NULL DEFAULT false, "hiddenFromContinueWatching" boolean NOT NULL DEFAULT false, "lastPlayedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "playedAt" TIMESTAMP WITH TIME ZONE, "userId" integer, "mediaId" integer, "mediaFileId" integer, "episodeId" integer, CONSTRAINT "PK_40ce4d415c9dcfaf467b7473614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_227d23190a49e5c40c6a4ccedd" ON "playback_states" ("userId", "episodeId", "completed") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb83c621e1daf59140e1e1be0a" ON "playback_states" ("userId", "completed", "lastPlayedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a650813641a2f4136cfd6ae5a8" ON "playback_states" ("userId", "mediaId", "completed") `);
        await queryRunner.query(`CREATE TABLE "app_settings" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "key" character varying NOT NULL, "value" text, CONSTRAINT "UQ_975c2db59c65c05fd9c6b63a2ab" UNIQUE ("key"), CONSTRAINT "PK_4800b266ba790931744b3e53a74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stalled_checks" ("id" SERIAL NOT NULL, "torrentHash" character varying(64) NOT NULL, "downloadedBytes" bigint NOT NULL, "checkedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a0cadae9926d53336db16357d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f0818a4bdb84ecb098bc6bed39" ON "stalled_checks" ("torrentHash", "checkedAt") `);
        await queryRunner.query(`CREATE TABLE "commands" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'queued', "startedOn" TIMESTAMP WITH TIME ZONE, "endedOn" TIMESTAMP WITH TIME ZONE, "trigger" character varying NOT NULL DEFAULT 'manual', "body" jsonb, CONSTRAINT "PK_7ac292c3aa19300482b2b190d1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "request_comments" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "message" text NOT NULL, "requestId" integer, "userId" integer, CONSTRAINT "PK_c2828c911aaf4d21408bc1e03e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."requests_mediatype_enum" AS ENUM('movie', 'series')`);
        await queryRunner.query(`CREATE TYPE "public"."requests_status_enum" AS ENUM('pending', 'approved', 'declined', 'processing', 'available', 'failed')`);
        await queryRunner.query(`CREATE TABLE "requests" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "mediaType" "public"."requests_mediatype_enum" NOT NULL, "tmdbId" integer NOT NULL, "title" character varying NOT NULL, "status" "public"."requests_status_enum" NOT NULL DEFAULT 'pending', "declinedReason" text, "seasons" jsonb, "userId" integer, "approvedById" integer, "qualityProfileId" integer, "languageProfileId" integer, "rootFolderId" integer, "libraryId" integer, "mediaId" integer, CONSTRAINT "PK_0428f484e96f9e6a55955f29b5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auto_approval_rules" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "conditions" jsonb NOT NULL, "priority" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_e15edc2d64990ed78a3a34b12b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quality_definitions" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "qualityId" integer NOT NULL, "title" character varying NOT NULL, "minSize" double precision NOT NULL DEFAULT '0', "preferredSize" double precision NOT NULL DEFAULT '0', "maxSize" double precision NOT NULL DEFAULT '0', CONSTRAINT "UQ_5f4831d8cb9a9bc845a98006aeb" UNIQUE ("qualityId"), CONSTRAINT "PK_ac863a00261a01b83b7677c2039" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delay_profiles" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "torrentDelay" integer NOT NULL DEFAULT '0', "order" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_0fdbcfaa90c5e6ee74b4639e3d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_connections" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "type" character varying NOT NULL, "settings" jsonb NOT NULL DEFAULT '{}', "events" jsonb NOT NULL DEFAULT '[]', "enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b77540d9ad6ca4ac46e5db9f26d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "custom_formats" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "score" integer NOT NULL DEFAULT '0', "specifications" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_076675654bab65414d7c59160eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "indexers" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "implementation" character varying NOT NULL, "settings" jsonb NOT NULL DEFAULT '{}', "enableRss" boolean NOT NULL DEFAULT true, "enableSearch" boolean NOT NULL DEFAULT true, "priority" integer NOT NULL DEFAULT '25', "enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_ae1fdd208e71fc3e9c87353bb7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "download_clients" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "implementation" character varying NOT NULL, "settings" jsonb NOT NULL DEFAULT '{}', "enabled" boolean NOT NULL DEFAULT true, "priority" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_294db9704d1ebc6bd77942f4d69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "download_history" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "sourceTitle" character varying NOT NULL, "quality" character varying NOT NULL, "language" character varying, "torrentHash" character varying, "status" character varying NOT NULL DEFAULT 'grabbed', "statusMessage" text, "grabSource" character varying(8) NOT NULL DEFAULT 'auto', "mediaId" integer, "indexerId" integer, "downloadClientId" integer, CONSTRAINT "PK_7e4f2648a1c62daab122d86dde5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "episode_markers" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying(16) NOT NULL, "startSeconds" double precision NOT NULL, "endSeconds" double precision NOT NULL, "confidence" double precision NOT NULL DEFAULT '1', "manual" boolean NOT NULL DEFAULT false, "episodeId" integer, CONSTRAINT "uq_episode_marker_type" UNIQUE ("episodeId", "type"), CONSTRAINT "PK_47780a1be9b93671c0286aedc06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "library_user_access" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "libraryId" integer, "userId" integer, CONSTRAINT "UQ_b5a9b3a47bd7b60b3cd2a778b18" UNIQUE ("libraryId", "userId"), CONSTRAINT "PK_dbd08312a26a16b56702859aa31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "indexer_stats" ("id" SERIAL NOT NULL, "queryDate" TIMESTAMP NOT NULL DEFAULT now(), "queryType" character varying NOT NULL DEFAULT 'search', "responseTimeMs" integer NOT NULL DEFAULT '0', "resultCount" integer NOT NULL DEFAULT '0', "errorMessage" text, "indexerId" integer, CONSTRAINT "PK_c8a3327cda357324f33dd41530f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cleanup_profiles" ("key" character varying(16) NOT NULL, "samples" integer NOT NULL, "intervalMinutes" integer NOT NULL, "autoRestart" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_51c4351ec9daef3fbdf1c0136a4" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "blocklist" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "sourceTitle" character varying NOT NULL, "indexerName" character varying, "downloadUrl" character varying, "quality" character varying, "note" character varying, "indexerId" integer, "mediaId" integer, "userId" integer, CONSTRAINT "PK_c3a1a2ea2ffda610496ce852572" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pairing_requests" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "publicId" character varying NOT NULL, "userId" integer NOT NULL, "deviceId" character varying NOT NULL, "deviceName" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "approvedByUserId" integer, "accessToken" text, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_afa67f327d1abc474061454d0e8" UNIQUE ("publicId"), CONSTRAINT "PK_a088c08f7ba12dc7c2fa652cdb9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_afa67f327d1abc474061454d0e" ON "pairing_requests" ("publicId") `);
        await queryRunner.query(`CREATE INDEX "IDX_35326c2d082f6619e340bc365f" ON "pairing_requests" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_590ddc457345bff7d6a9c70416" ON "pairing_requests" ("deviceId") `);
        await queryRunner.query(`CREATE TABLE "role_default_libraries" ("roleId" integer NOT NULL, "libraryId" integer NOT NULL, CONSTRAINT "PK_c7acdb10cc62d7d2a1b57443de3" PRIMARY KEY ("roleId", "libraryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_642c4b48b2c022d0baae6cc122" ON "role_default_libraries" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f3a35a769725163823e1162a9" ON "role_default_libraries" ("libraryId") `);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb83c621e1daf59140e1e1be0a"`);
        await queryRunner.query(`CREATE INDEX "IDX_eb83c621e1daf59140e1e1be0a" ON "playback_states" ("userId", "completed", "lastPlayedAt") `);
        await queryRunner.query(`ALTER TABLE "root_folders" ADD CONSTRAINT "FK_778e970653757cf9f35ca2bf360" FOREIGN KEY ("libraryId") REFERENCES "libraries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "libraries" ADD CONSTRAINT "FK_1127dccf41a2959b675a0aa8891" FOREIGN KEY ("defaultQualityProfileId") REFERENCES "quality_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "libraries" ADD CONSTRAINT "FK_68b96c817fab521697d7a087685" FOREIGN KEY ("defaultLanguageProfileId") REFERENCES "language_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtitle_provider_stats" ADD CONSTRAINT "FK_0bd2f50e4e0a883545fde657094" FOREIGN KEY ("providerId") REFERENCES "subtitle_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "episodes" ADD CONSTRAINT "FK_b312e9d94c9b80adee2330b73e9" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seasons" ADD CONSTRAINT "FK_5e53591a9fd2dbb7f297863ecc6" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_files" ADD CONSTRAINT "FK_d9ebcae21d44cc576a4f569486d" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_files" ADD CONSTRAINT "FK_6b32aaee05883e7fc772e29db28" FOREIGN KEY ("episodeId") REFERENCES "episodes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_metadata" ADD CONSTRAINT "FK_62d457c000de0f01b2821a06ae6" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_cast" ADD CONSTRAINT "FK_6cc8df2e63ef1cd8cf28bfc854a" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_cast" ADD CONSTRAINT "FK_f702d61f4cd1578c889ab3cadca" FOREIGN KEY ("personId") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_crew" ADD CONSTRAINT "FK_95c3254f4a9023b7f30c81c25fa" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_crew" ADD CONSTRAINT "FK_8226529bf8b570cefa0bad2f96a" FOREIGN KEY ("personId") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_ecd8a0e3718ba485b1cfffd5999" FOREIGN KEY ("rootFolderId") REFERENCES "root_folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_bf4a42ddf842b0536fcd81b4f2b" FOREIGN KEY ("libraryId") REFERENCES "libraries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_6cde0e5015d20edcd45f593d27b" FOREIGN KEY ("qualityProfileId") REFERENCES "quality_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_fb0eb80298f112ac0bfb103da0e" FOREIGN KEY ("languageProfileId") REFERENCES "language_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtitle_files" ADD CONSTRAINT "FK_38e603e48e77e016bc9cc88cafd" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtitle_files" ADD CONSTRAINT "FK_9fd8637cb821ddec6f57b422785" FOREIGN KEY ("episodeId") REFERENCES "episodes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtitle_files" ADD CONSTRAINT "FK_fad8b97f2b3863e76aae917e94d" FOREIGN KEY ("mediaFileId") REFERENCES "media_files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtitle_blacklist" ADD CONSTRAINT "FK_e0508dc1dd297c4cc01044f228c" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_states" ADD CONSTRAINT "FK_badc34ed0e95631af673a5d981d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_states" ADD CONSTRAINT "FK_742bc2fe139bc8334edab814e16" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_states" ADD CONSTRAINT "FK_b01f3bfb9c8dcbca9c0030341b3" FOREIGN KEY ("mediaFileId") REFERENCES "media_files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_states" ADD CONSTRAINT "FK_868d7ead9d6748409edee2b7b4a" FOREIGN KEY ("episodeId") REFERENCES "episodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_comments" ADD CONSTRAINT "FK_83f2ec25950f32fb4930d0b733f" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_comments" ADD CONSTRAINT "FK_c03e315afb98705e644633d80b7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_be846ad4b43f40acc7034ef7f40" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_93dd6ea962d8a48df3f7448bdd5" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_4340ea3e8eb488c8cb4edbcc468" FOREIGN KEY ("qualityProfileId") REFERENCES "quality_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_6ac8127d11e259d8feb3a1c77c4" FOREIGN KEY ("languageProfileId") REFERENCES "language_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_11390ba18a01b3f758bd13dd7b0" FOREIGN KEY ("rootFolderId") REFERENCES "root_folders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_c6cb47d29a66465e0489a770be8" FOREIGN KEY ("libraryId") REFERENCES "libraries"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_d9b24c2cc987bf39be9bd481fc5" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "download_history" ADD CONSTRAINT "FK_e8096477351ee7e5f34a84b3db4" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "download_history" ADD CONSTRAINT "FK_f7f953fd61bd20b284c0d65e9b4" FOREIGN KEY ("indexerId") REFERENCES "indexers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "download_history" ADD CONSTRAINT "FK_ad623713407adce2bfac231b7c9" FOREIGN KEY ("downloadClientId") REFERENCES "download_clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "episode_markers" ADD CONSTRAINT "FK_b4ef632c24f24a5e7b9c4e18a4e" FOREIGN KEY ("episodeId") REFERENCES "episodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "library_user_access" ADD CONSTRAINT "FK_644d5c1672d256a02073eec76d6" FOREIGN KEY ("libraryId") REFERENCES "libraries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "library_user_access" ADD CONSTRAINT "FK_32958f30dee035e832a2234763d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "indexer_stats" ADD CONSTRAINT "FK_2173b013658d283c7fb43de69d3" FOREIGN KEY ("indexerId") REFERENCES "indexers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocklist" ADD CONSTRAINT "FK_c0ad3d19ab0e2d7edb3b6468a7b" FOREIGN KEY ("indexerId") REFERENCES "indexers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocklist" ADD CONSTRAINT "FK_5c8af2d0e83b3be6d250eccc19d" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocklist" ADD CONSTRAINT "FK_356721a49f145aa439c16e6b999" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_default_libraries" ADD CONSTRAINT "FK_642c4b48b2c022d0baae6cc1226" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_default_libraries" ADD CONSTRAINT "FK_7f3a35a769725163823e1162a98" FOREIGN KEY ("libraryId") REFERENCES "libraries"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_default_libraries" DROP CONSTRAINT "FK_7f3a35a769725163823e1162a98"`);
        await queryRunner.query(`ALTER TABLE "role_default_libraries" DROP CONSTRAINT "FK_642c4b48b2c022d0baae6cc1226"`);
        await queryRunner.query(`ALTER TABLE "blocklist" DROP CONSTRAINT "FK_356721a49f145aa439c16e6b999"`);
        await queryRunner.query(`ALTER TABLE "blocklist" DROP CONSTRAINT "FK_5c8af2d0e83b3be6d250eccc19d"`);
        await queryRunner.query(`ALTER TABLE "blocklist" DROP CONSTRAINT "FK_c0ad3d19ab0e2d7edb3b6468a7b"`);
        await queryRunner.query(`ALTER TABLE "indexer_stats" DROP CONSTRAINT "FK_2173b013658d283c7fb43de69d3"`);
        await queryRunner.query(`ALTER TABLE "library_user_access" DROP CONSTRAINT "FK_32958f30dee035e832a2234763d"`);
        await queryRunner.query(`ALTER TABLE "library_user_access" DROP CONSTRAINT "FK_644d5c1672d256a02073eec76d6"`);
        await queryRunner.query(`ALTER TABLE "episode_markers" DROP CONSTRAINT "FK_b4ef632c24f24a5e7b9c4e18a4e"`);
        await queryRunner.query(`ALTER TABLE "download_history" DROP CONSTRAINT "FK_ad623713407adce2bfac231b7c9"`);
        await queryRunner.query(`ALTER TABLE "download_history" DROP CONSTRAINT "FK_f7f953fd61bd20b284c0d65e9b4"`);
        await queryRunner.query(`ALTER TABLE "download_history" DROP CONSTRAINT "FK_e8096477351ee7e5f34a84b3db4"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_d9b24c2cc987bf39be9bd481fc5"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_c6cb47d29a66465e0489a770be8"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_11390ba18a01b3f758bd13dd7b0"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_6ac8127d11e259d8feb3a1c77c4"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_4340ea3e8eb488c8cb4edbcc468"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_93dd6ea962d8a48df3f7448bdd5"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_be846ad4b43f40acc7034ef7f40"`);
        await queryRunner.query(`ALTER TABLE "request_comments" DROP CONSTRAINT "FK_c03e315afb98705e644633d80b7"`);
        await queryRunner.query(`ALTER TABLE "request_comments" DROP CONSTRAINT "FK_83f2ec25950f32fb4930d0b733f"`);
        await queryRunner.query(`ALTER TABLE "playback_states" DROP CONSTRAINT "FK_868d7ead9d6748409edee2b7b4a"`);
        await queryRunner.query(`ALTER TABLE "playback_states" DROP CONSTRAINT "FK_b01f3bfb9c8dcbca9c0030341b3"`);
        await queryRunner.query(`ALTER TABLE "playback_states" DROP CONSTRAINT "FK_742bc2fe139bc8334edab814e16"`);
        await queryRunner.query(`ALTER TABLE "playback_states" DROP CONSTRAINT "FK_badc34ed0e95631af673a5d981d"`);
        await queryRunner.query(`ALTER TABLE "subtitle_blacklist" DROP CONSTRAINT "FK_e0508dc1dd297c4cc01044f228c"`);
        await queryRunner.query(`ALTER TABLE "subtitle_files" DROP CONSTRAINT "FK_fad8b97f2b3863e76aae917e94d"`);
        await queryRunner.query(`ALTER TABLE "subtitle_files" DROP CONSTRAINT "FK_9fd8637cb821ddec6f57b422785"`);
        await queryRunner.query(`ALTER TABLE "subtitle_files" DROP CONSTRAINT "FK_38e603e48e77e016bc9cc88cafd"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_fb0eb80298f112ac0bfb103da0e"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_6cde0e5015d20edcd45f593d27b"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_bf4a42ddf842b0536fcd81b4f2b"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_ecd8a0e3718ba485b1cfffd5999"`);
        await queryRunner.query(`ALTER TABLE "media_crew" DROP CONSTRAINT "FK_8226529bf8b570cefa0bad2f96a"`);
        await queryRunner.query(`ALTER TABLE "media_crew" DROP CONSTRAINT "FK_95c3254f4a9023b7f30c81c25fa"`);
        await queryRunner.query(`ALTER TABLE "media_cast" DROP CONSTRAINT "FK_f702d61f4cd1578c889ab3cadca"`);
        await queryRunner.query(`ALTER TABLE "media_cast" DROP CONSTRAINT "FK_6cc8df2e63ef1cd8cf28bfc854a"`);
        await queryRunner.query(`ALTER TABLE "media_metadata" DROP CONSTRAINT "FK_62d457c000de0f01b2821a06ae6"`);
        await queryRunner.query(`ALTER TABLE "media_files" DROP CONSTRAINT "FK_6b32aaee05883e7fc772e29db28"`);
        await queryRunner.query(`ALTER TABLE "media_files" DROP CONSTRAINT "FK_d9ebcae21d44cc576a4f569486d"`);
        await queryRunner.query(`ALTER TABLE "seasons" DROP CONSTRAINT "FK_5e53591a9fd2dbb7f297863ecc6"`);
        await queryRunner.query(`ALTER TABLE "episodes" DROP CONSTRAINT "FK_b312e9d94c9b80adee2330b73e9"`);
        await queryRunner.query(`ALTER TABLE "subtitle_provider_stats" DROP CONSTRAINT "FK_0bd2f50e4e0a883545fde657094"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "libraries" DROP CONSTRAINT "FK_68b96c817fab521697d7a087685"`);
        await queryRunner.query(`ALTER TABLE "libraries" DROP CONSTRAINT "FK_1127dccf41a2959b675a0aa8891"`);
        await queryRunner.query(`ALTER TABLE "root_folders" DROP CONSTRAINT "FK_778e970653757cf9f35ca2bf360"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb83c621e1daf59140e1e1be0a"`);
        await queryRunner.query(`CREATE INDEX "IDX_eb83c621e1daf59140e1e1be0a" ON "playback_states" ("userId", "completed", "lastPlayedAt") `);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f3a35a769725163823e1162a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_642c4b48b2c022d0baae6cc122"`);
        await queryRunner.query(`DROP TABLE "role_default_libraries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_590ddc457345bff7d6a9c70416"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35326c2d082f6619e340bc365f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afa67f327d1abc474061454d0e"`);
        await queryRunner.query(`DROP TABLE "pairing_requests"`);
        await queryRunner.query(`DROP TABLE "blocklist"`);
        await queryRunner.query(`DROP TABLE "cleanup_profiles"`);
        await queryRunner.query(`DROP TABLE "indexer_stats"`);
        await queryRunner.query(`DROP TABLE "library_user_access"`);
        await queryRunner.query(`DROP TABLE "episode_markers"`);
        await queryRunner.query(`DROP TABLE "download_history"`);
        await queryRunner.query(`DROP TABLE "download_clients"`);
        await queryRunner.query(`DROP TABLE "indexers"`);
        await queryRunner.query(`DROP TABLE "custom_formats"`);
        await queryRunner.query(`DROP TABLE "notification_connections"`);
        await queryRunner.query(`DROP TABLE "delay_profiles"`);
        await queryRunner.query(`DROP TABLE "quality_definitions"`);
        await queryRunner.query(`DROP TABLE "auto_approval_rules"`);
        await queryRunner.query(`DROP TABLE "requests"`);
        await queryRunner.query(`DROP TYPE "public"."requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."requests_mediatype_enum"`);
        await queryRunner.query(`DROP TABLE "request_comments"`);
        await queryRunner.query(`DROP TABLE "commands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0818a4bdb84ecb098bc6bed39"`);
        await queryRunner.query(`DROP TABLE "stalled_checks"`);
        await queryRunner.query(`DROP TABLE "app_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a650813641a2f4136cfd6ae5a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb83c621e1daf59140e1e1be0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_227d23190a49e5c40c6a4ccedd"`);
        await queryRunner.query(`DROP TABLE "playback_states"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_recommendation_dismissals_user_media"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2675281c4a4e36f69c7a07bff7"`);
        await queryRunner.query(`DROP TABLE "recommendation_dismissals"`);
        await queryRunner.query(`DROP TABLE "subtitle_blacklist"`);
        await queryRunner.query(`DROP TABLE "subtitle_files"`);
        await queryRunner.query(`DROP TYPE "public"."subtitle_files_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subtitle_files_providertype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_media_type_tmdbId"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TYPE "public"."media_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95c3254f4a9023b7f30c81c25f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8226529bf8b570cefa0bad2f96"`);
        await queryRunner.query(`DROP TABLE "media_crew"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cc8df2e63ef1cd8cf28bfc854"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f702d61f4cd1578c889ab3cadc"`);
        await queryRunner.query(`DROP TABLE "media_cast"`);
        await queryRunner.query(`DROP TABLE "persons"`);
        await queryRunner.query(`DROP TABLE "media_metadata"`);
        await queryRunner.query(`DROP TABLE "media_files"`);
        await queryRunner.query(`DROP TABLE "seasons"`);
        await queryRunner.query(`DROP TABLE "episodes"`);
        await queryRunner.query(`DROP TABLE "subtitle_provider_stats"`);
        await queryRunner.query(`DROP TABLE "subtitle_providers"`);
        await queryRunner.query(`DROP TYPE "public"."subtitle_providers_type_enum"`);
        await queryRunner.query(`DROP TABLE "media_servers"`);
        await queryRunner.query(`DROP TYPE "public"."media_servers_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_mediaservertype_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "libraries"`);
        await queryRunner.query(`DROP TABLE "language_profiles"`);
        await queryRunner.query(`DROP TABLE "quality_profiles"`);
        await queryRunner.query(`DROP TABLE "root_folders"`);
    }

}
