import { Logger } from '@nestjs/common';
import { buildFfmpegArgs } from './ffmpeg-args';
import type { BuildFfmpegArgsOptions } from './ffmpeg-args';
import type { CodecVariant } from './codec/types';
import type { TranscodeProfile } from './types';

/**
 * Characterization (golden) snapshots of the ffmpeg argv for the CPU path.
 * CPU (`hwAccel: 'none'`) is fully deterministic and needs no GPU or boot probe
 * (an un-probed encoder is treated as enabled), so it can run in CI. These lock
 * the exact command the current builder emits so the upcoming staged
 * FfmpegCommand refactor (#plan §2) preserves the encode behaviour — a silent
 * argv change is how segment/manifest desync and decode regressions slip in.
 *
 * The QSV/VAAPI matrix below is also snapshotted: argv *building* is
 * deterministic and GPU-free (an un-probed encoder resolves as enabled), even
 * though *running* it needs the hardware. These lock the encoder/decoder/filter
 * resolution across SDR / HDR / tonemap / crop so the resolveEncodePipeline
 * extraction stays byte-identical.
 */

const silentLog = {
  debug: () => {},
  log: () => {},
  warn: () => {},
  error: () => {},
} as unknown as Logger;

const profile = (over: Partial<TranscodeProfile> = {}): TranscodeProfile => ({
  name: '1080p',
  maxWidth: 1920,
  maxHeight: 1080,
  videoBitrate: '8M',
  audioBitrate: '192k',
  ...over,
});

const H264_SDR: CodecVariant = { codec: 'h264', bitDepth: 8, hdr: null };
const HEVC_SDR: CodecVariant = { codec: 'hevc', bitDepth: 8, hdr: null };
const HEVC_HDR10: CodecVariant = { codec: 'hevc', bitDepth: 10, hdr: 'HDR10' };
const AV1_HDR10: CodecVariant = { codec: 'av1', bitDepth: 10, hdr: 'HDR10' };

const CROP_4K = { width: 3840, height: 1632, x: 0, y: 264 };
const HDR_4K = {
  sourceWidth: 3840,
  sourceHeight: 2160,
  sourceBitDepth: 10,
} as const;
const PROFILE_4K = { name: '2160p', maxWidth: 3840, maxHeight: 2160 };

const opts = (over: Partial<BuildFfmpegArgsOptions>): BuildFfmpegArgsOptions =>
  ({
    inputPath: '/media/in.mkv',
    outputDir: '/cache/out',
    hwAccel: 'none',
    profile: profile(),
    videoVariant: H264_SDR,
    sourceWidth: 1920,
    sourceHeight: 1080,
    sourceFps: 24,
    trustedStreamInfo: true,
    ...over,
  }) as BuildFfmpegArgsOptions;

describe('buildFfmpegArgs — CPU golden argv (characterization)', () => {
  it('H.264 SDR 1080p transcode', () => {
    expect(buildFfmpegArgs(opts({}), silentLog)).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libx264",
       "-threads:v",
       "4",
       "-preset",
       "veryfast",
       "-profile:v",
       "high",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-bufsize",
       "16M",
       "-vf",
       "scale=1920:ceil(ih*1920/iw/2)*2:flags=lanczos,format=yuv420p",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-sc_threshold:v:0",
       "0",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('HEVC HDR10 10-bit transcode (libx265, HDR metadata preserved)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          profile: profile({
            name: '2160p-hdr',
            maxWidth: 3840,
            maxHeight: 2160,
            videoBitrate: '28M',
          }),
          videoVariant: HEVC_HDR10,
          sourceWidth: 3840,
          sourceHeight: 2160,
          sourceBitDepth: 10,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libx265",
       "-threads:v",
       "4",
       "-preset",
       "faster",
       "-pix_fmt",
       "yuv420p10le",
       "-b:v",
       "25000000",
       "-maxrate",
       "25000000",
       "-vf",
       "scale=3840:ceil(ih*3840/iw/2)*2:flags=lanczos,format=yuv420p10le",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-x265-params",
       "hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1):max-cll=1000,400",
       "-color_primaries",
       "bt2020",
       "-color_trc",
       "smpte2084",
       "-colorspace",
       "bt2020nc",
       "-tag:v",
       "hvc1",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('HEVC HDR10 -> SDR tonemap (CPU tonemap filter chain)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          videoVariant: H264_SDR,
          tonemap: true,
          sourceBitDepth: 10,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libx264",
       "-threads:v",
       "4",
       "-preset",
       "veryfast",
       "-profile:v",
       "high",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-bufsize",
       "16M",
       "-vf",
       "format=gbrpf32le,tonemap=mobius:desat=0,format=yuv420p,scale=1920:ceil(ih*1920/iw/2)*2:flags=lanczos,format=yuv420p",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-sc_threshold:v:0",
       "0",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('image subtitle burn-in: overlay via -filter_complex, no -vf, maps [vout]', () => {
    const args = buildFfmpegArgs(
      opts({ burnIn: { filter: null, type: 'image', streamIndex: 3 } }),
      silentLog,
    );
    expect(args).not.toContain('-vf');
    const fcIdx = args.indexOf('-filter_complex');
    expect(fcIdx).toBeGreaterThan(-1);
    const fc = args[fcIdx + 1];
    // Reuses the encoder's video chain, composites the sub in RGB, back to YUV.
    expect(fc).toContain(
      '[0:v]scale=1920:ceil(ih*1920/iw/2)*2:flags=lanczos,format=yuv420p,format=rgb24[v]',
    );
    expect(fc).toContain(
      '[0:3]scale=1920:1080:flags=lanczos,format=rgba,colorlevels=rimax=0.6:gimax=0.6:bimax=0.6[s]',
    );
    expect(fc).toContain('[v][s]overlay[ov]');
    expect(fc).toContain('[ov]format=yuv420p[vout]');
    expect(args).toContain('[vout]');
    expect(args).not.toContain('0:v:0');
  });

  it('image subtitle burn-in: crops the overlay identically to the video', () => {
    const args = buildFfmpegArgs(
      opts({
        crop: CROP_4K,
        sourceWidth: 3840,
        sourceHeight: 2160,
        burnIn: { filter: null, type: 'image', streamIndex: 3 },
      }),
      silentLog,
    );
    const fc = args[args.indexOf('-filter_complex') + 1];
    // The PGS overlay is authored against the full source frame, so it gets the
    // same crop as the video before scaling — otherwise it reads oversized.
    expect(fc).toContain('[0:3]crop=3840:1632:0:264,scale=');
  });
});

describe('buildFfmpegArgs — QSV/VAAPI matrix golden argv (characterization)', () => {
  it('QSV HEVC SDR 1080p', () => {
    expect(
      buildFfmpegArgs(
        opts({ hwAccel: 'qsv', videoVariant: HEVC_SDR }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-init_hw_device",
       "vaapi=va:/dev/dri/renderD128",
       "-init_hw_device",
       "qsv=qs@va",
       "-hwaccel",
       "vaapi",
       "-hwaccel_output_format",
       "vaapi",
       "-hwaccel_device",
       "va",
       "-extra_hw_frames",
       "32",
       "-noautorotate",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "hevc_qsv",
       "-preset",
       "faster",
       "-forced_idr",
       "1",
       "-adaptive_i",
       "0",
       "-bf",
       "0",
       "-b_strategy",
       "0",
       "-mbbrc",
       "1",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000001",
       "-rc_init_occupancy",
       "8000000",
       "-bufsize",
       "8000000",
       "-vf",
       "scale_vaapi=w=1920:h=-2:format=nv12:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-tag:v",
       "hvc1",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('QSV HEVC HDR10 4K (Main10, no tonemap)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          hwAccel: 'qsv',
          videoVariant: HEVC_HDR10,
          profile: profile(PROFILE_4K),
          ...HDR_4K,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "hevc_qsv",
       "-profile:v",
       "main10",
       "-preset",
       "faster",
       "-forced_idr",
       "1",
       "-adaptive_i",
       "0",
       "-bf",
       "0",
       "-b_strategy",
       "0",
       "-mbbrc",
       "1",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000001",
       "-rc_init_occupancy",
       "8000000",
       "-bufsize",
       "8000000",
       "-vf",
       "scale_vaapi=w=3840:h=-2:format=p010le:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-color_primaries",
       "bt2020",
       "-color_trc",
       "smpte2084",
       "-colorspace",
       "bt2020nc",
       "-tag:v",
       "hvc1",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('QSV HEVC HDR10 -> SDR tonemap (H.264 out)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          hwAccel: 'qsv',
          videoVariant: H264_SDR,
          tonemap: true,
          profile: profile(PROFILE_4K),
          ...HDR_4K,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "h264_qsv",
       "-preset",
       "faster",
       "-forced_idr",
       "1",
       "-adaptive_i",
       "0",
       "-bf",
       "0",
       "-b_strategy",
       "0",
       "-mbbrc",
       "1",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000001",
       "-rc_init_occupancy",
       "8000000",
       "-bufsize",
       "8000000",
       "-vf",
       "scale_vaapi=w=3840:h=-2:extra_hw_frames=24,tonemap_vaapi=format=nv12:t=bt709:p=bt709:m=bt709,hwmap=derive_device=qsv,format=qsv",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('QSV HEVC SDR crop (cropped 4K)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          hwAccel: 'qsv',
          videoVariant: HEVC_SDR,
          crop: CROP_4K,
          profile: profile(PROFILE_4K),
          sourceWidth: 3840,
          sourceHeight: 2160,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-init_hw_device",
       "vaapi=va:/dev/dri/renderD128",
       "-filter_hw_device",
       "va",
       "-hwaccel",
       "vaapi",
       "-hwaccel_output_format",
       "vaapi",
       "-hwaccel_device",
       "va",
       "-extra_hw_frames",
       "32",
       "-noautorotate",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "hevc_vaapi",
       "-profile:v",
       "1",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-vf",
       "hwdownload,format=nv12,crop=3840:1632:0:264,hwupload=derive_device=vaapi,scale_vaapi=w=3840:h=-2:format=nv12",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-tag:v",
       "hvc1",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('QSV HEVC HDR crop + tonemap (cropped 4K HDR -> SDR)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          hwAccel: 'qsv',
          videoVariant: H264_SDR,
          crop: CROP_4K,
          tonemap: true,
          profile: profile(PROFILE_4K),
          ...HDR_4K,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "h264_qsv",
       "-preset",
       "faster",
       "-forced_idr",
       "1",
       "-adaptive_i",
       "0",
       "-bf",
       "0",
       "-b_strategy",
       "0",
       "-mbbrc",
       "1",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000001",
       "-rc_init_occupancy",
       "8000000",
       "-bufsize",
       "8000000",
       "-vf",
       "hwdownload,format=p010le,crop=3840:1632:0:264,hwupload=derive_device=vaapi,scale_vaapi=w=3840:h=-2:extra_hw_frames=24,tonemap_vaapi=format=nv12:t=bt709:p=bt709:m=bt709,hwmap=derive_device=qsv,format=qsv",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('QSV AV1 HDR10 4K', () => {
    expect(
      buildFfmpegArgs(
        opts({
          hwAccel: 'qsv',
          videoVariant: AV1_HDR10,
          profile: profile(PROFILE_4K),
          ...HDR_4K,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libsvtav1",
       "-pix_fmt",
       "yuv420p10le",
       "-preset",
       "9",
       "-b:v",
       "8000000",
       "-maxrate",
       "12000000",
       "-bufsize",
       "16000000",
       "-svtav1-params",
       "enable-hdr=1:mastering-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1):content-light=1000,400",
       "-vf",
       "scale=3840:ceil(ih*3840/iw/2)*2:flags=lanczos,format=yuv420p10le",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-color_primaries",
       "bt2020",
       "-color_trc",
       "smpte2084",
       "-colorspace",
       "bt2020nc",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('VAAPI HEVC SDR 1080p', () => {
    expect(
      buildFfmpegArgs(
        opts({ hwAccel: 'vaapi', videoVariant: HEVC_SDR }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-init_hw_device",
       "vaapi=va:/dev/dri/renderD128",
       "-filter_hw_device",
       "va",
       "-hwaccel",
       "vaapi",
       "-hwaccel_output_format",
       "vaapi",
       "-hwaccel_device",
       "va",
       "-extra_hw_frames",
       "32",
       "-noautorotate",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "hevc_vaapi",
       "-profile:v",
       "1",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-vf",
       "scale_vaapi=w=1920:h=-2:format=nv12",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-tag:v",
       "hvc1",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('VAAPI HEVC HDR10 4K', () => {
    expect(
      buildFfmpegArgs(
        opts({
          hwAccel: 'vaapi',
          videoVariant: HEVC_HDR10,
          profile: profile(PROFILE_4K),
          ...HDR_4K,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libx265",
       "-threads:v",
       "4",
       "-preset",
       "faster",
       "-pix_fmt",
       "yuv420p10le",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-vf",
       "scale=3840:ceil(ih*3840/iw/2)*2:flags=lanczos,format=yuv420p10le",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-x265-params",
       "hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1):max-cll=1000,400",
       "-color_primaries",
       "bt2020",
       "-color_trc",
       "smpte2084",
       "-colorspace",
       "bt2020nc",
       "-tag:v",
       "hvc1",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('VAAPI HEVC HDR crop + tonemap (cropped 4K HDR -> SDR)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          hwAccel: 'vaapi',
          videoVariant: H264_SDR,
          crop: CROP_4K,
          tonemap: true,
          profile: profile(PROFILE_4K),
          ...HDR_4K,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "h264_vaapi",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-vf",
       "hwdownload,format=p010le,crop=3840:1632:0:264,hwupload=derive_device=vaapi,scale_vaapi=w=3840:h=-2:extra_hw_frames=24,tonemap_vaapi=format=nv12:t=bt709:p=bt709:m=bt709",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });
});
