import { Logger } from '@nestjs/common';
import { buildFfmpegArgs } from './ffmpeg-args';
import type { BuildFfmpegArgsOptions } from './ffmpeg-args';
import type { CodecVariant } from './codec/types';
import type { TranscodeProfile } from './types';

/**
 * Characterization (golden) snapshots of the ffmpeg argv for the CPU path.
 * CPU (`hwAccel: 'none'`) is fully deterministic and needs no GPU or boot probe
 * (an un-probed encoder is treated as enabled), so it can run in CI. These lock
 * the exact command the current builder emits so the upcoming staged
 * FfmpegCommand refactor (#plan §2) preserves the encode behaviour — a silent
 * argv change is how segment/manifest desync and decode regressions slip in.
 *
 * The HW paths (qsv/vaapi/nvenc/videotoolbox) are intentionally NOT snapshotted
 * here — they require the matching hardware/driver to even resolve an encoder.
 */

const silentLog = {
  debug: () => {},
  log: () => {},
  warn: () => {},
  error: () => {},
} as unknown as Logger;

const profile = (over: Partial<TranscodeProfile> = {}): TranscodeProfile => ({
  name: '1080p',
  maxWidth: 1920,
  maxHeight: 1080,
  videoBitrate: '8M',
  audioBitrate: '192k',
  ...over,
});

const H264_SDR: CodecVariant = { codec: 'h264', bitDepth: 8, hdr: null };
const HEVC_HDR10: CodecVariant = { codec: 'hevc', bitDepth: 10, hdr: 'HDR10' };

const opts = (over: Partial<BuildFfmpegArgsOptions>): BuildFfmpegArgsOptions =>
  ({
    inputPath: '/media/in.mkv',
    outputDir: '/cache/out',
    hwAccel: 'none',
    profile: profile(),
    videoVariant: H264_SDR,
    sourceWidth: 1920,
    sourceHeight: 1080,
    sourceFps: 24,
    trustedStreamInfo: true,
    ...over,
  }) as BuildFfmpegArgsOptions;

describe('buildFfmpegArgs — CPU golden argv (characterization)', () => {
  it('H.264 SDR 1080p transcode', () => {
    expect(buildFfmpegArgs(opts({}), silentLog)).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libx264",
       "-threads:v",
       "4",
       "-preset",
       "veryfast",
       "-profile:v",
       "high",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-bufsize",
       "16M",
       "-vf",
       "scale=1920:ceil(ih*1920/iw/2)*2:flags=lanczos,format=yuv420p",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-sc_threshold:v:0",
       "0",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('HEVC HDR10 10-bit transcode (libx265, HDR metadata preserved)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          profile: profile({
            name: '2160p-hdr',
            maxWidth: 3840,
            maxHeight: 2160,
            videoBitrate: '28M',
          }),
          videoVariant: HEVC_HDR10,
          sourceWidth: 3840,
          sourceHeight: 2160,
          sourceBitDepth: 10,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libx265",
       "-threads:v",
       "4",
       "-preset",
       "faster",
       "-pix_fmt",
       "yuv420p10le",
       "-b:v",
       "25000000",
       "-maxrate",
       "25000000",
       "-vf",
       "scale=3840:ceil(ih*3840/iw/2)*2:flags=lanczos,format=yuv420p10le",
       "-g",
       "72",
       "-keyint_min",
       "72",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-x265-params",
       "hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1):max-cll=1000,400",
       "-color_primaries",
       "bt2020",
       "-color_trc",
       "smpte2084",
       "-colorspace",
       "bt2020nc",
       "-tag:v",
       "hvc1",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });

  it('HEVC HDR10 -> SDR tonemap (CPU tonemap filter chain)', () => {
    expect(
      buildFfmpegArgs(
        opts({
          videoVariant: H264_SDR,
          tonemap: true,
          sourceBitDepth: 10,
        }),
        silentLog,
      ),
    ).toMatchInlineSnapshot(`
     [
       "-hide_banner",
       "-loglevel",
       "warning",
       "-analyzeduration",
       "0",
       "-probesize",
       "5000000",
       "-i",
       "/media/in.mkv",
       "-copyts",
       "-muxdelay",
       "0",
       "-muxpreload",
       "0",
       "-c:v",
       "libx264",
       "-threads:v",
       "4",
       "-preset",
       "veryfast",
       "-profile:v",
       "high",
       "-b:v",
       "8000000",
       "-maxrate",
       "8000000",
       "-bufsize",
       "16M",
       "-vf",
       "format=gbrpf32le,tonemap=mobius:desat=0,format=yuv420p,scale=1920:ceil(ih*1920/iw/2)*2:flags=lanczos,format=yuv420p",
       "-force_key_frames",
       "expr:gte(t,0+n_forced*3)",
       "-sc_threshold:v:0",
       "0",
       "-color_primaries",
       "bt709",
       "-color_trc",
       "bt709",
       "-colorspace",
       "bt709",
       "-color_range",
       "tv",
       "-map",
       "0:v:0",
       "-map",
       "0:a:0?",
       "-c:a",
       "aac",
       "-b:a",
       "192k",
       "-ac",
       "2",
       "-movflags",
       "+cmaf",
       "-f",
       "hls",
       "-hls_time",
       "3",
       "-hls_list_size",
       "0",
       "-start_number",
       "0",
       "-hls_segment_type",
       "fmp4",
       "-hls_fmp4_init_filename",
       "init.mp4",
       "-hls_segment_filename",
       "/cache/out/seg-%04d.m4s",
       "-hls_flags",
       "independent_segments+temp_file",
       "/cache/out/index.m3u8",
     ]
    `);
  });
});
